### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by ghost** [Gandi/ctld_exporter#2]
I've noticed that while running ctld_exporter consumes between 30-50+GB of memory.  Has anyone else noticed this?

**Comment by diconico07** [comment]
I noticed it as well, I made the fix in #3 but it isn't tested yet, feel free to test it and tell me if it works correctly. I will merge the PR and tag a new version if it fix the issue completely.

**Comment by ghost** [comment]
Great, will test today

**Comment by ghost** [comment]
Running for 24 hours, so far so good. Will give an update on Monday

**Comment by ghost** [comment]
Still running, only 220MB. Seems ok
